CREATE TABLE IF NOT EXISTS cellar_label_enrollments (
  id CHAR(36) NOT NULL,
  estate_id CHAR(36) NOT NULL,
  device_key_hash CHAR(64) NOT NULL,
  device_hint VARCHAR(32) NOT NULL,
  pairing_code CHAR(6) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'pending',
  display_name VARCHAR(160) NULL,
  device_role VARCHAR(24) NULL,
  destination_url VARCHAR(500) NULL,
  kiosk_id CHAR(36) NULL,
  expires_at DATETIME(6) NOT NULL,
  last_seen_at DATETIME(6) NULL,
  approved_at DATETIME(6) NULL,
  approved_by VARCHAR(190) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_cellar_label_enrollment_device (estate_id, device_key_hash),
  KEY idx_cellar_label_enrollment_status (estate_id, status, expires_at),
  KEY idx_cellar_label_enrollment_kiosk (kiosk_id),
  CONSTRAINT fk_cellar_label_enrollment_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_cellar_label_enrollment_kiosk FOREIGN KEY (kiosk_id) REFERENCES cellar_label_kiosks(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
