CREATE TABLE IF NOT EXISTS historical_cost_records (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  source_file_id VARCHAR(190) NOT NULL,
  source_file_name VARCHAR(255) NOT NULL,
  source_sheet VARCHAR(190) NOT NULL,
  source_row_number INT UNSIGNED NOT NULL,
  source_item_key VARCHAR(80) NOT NULL DEFAULT 'row',
  source_row_hash CHAR(64) NOT NULL,
  record_date DATE NULL,
  record_year SMALLINT UNSIGNED NULL,
  period_start_year SMALLINT UNSIGNED NULL,
  period_end_year SMALLINT UNSIGNED NULL,
  date_precision ENUM('day','month','year','period','unknown') NOT NULL DEFAULT 'unknown',
  record_kind ENUM('expense','compensation','payment','transfer') NOT NULL,
  classification VARCHAR(80) NULL,
  actor_name VARCHAR(160) NULL,
  description VARCHAR(1000) NOT NULL,
  amount_eur DECIMAL(14,2) NOT NULL,
  payment_method VARCHAR(120) NULL,
  payment_status VARCHAR(80) NULL,
  included_in_totals TINYINT(1) NOT NULL DEFAULT 1,
  duplicate_of CHAR(36) NULL,
  exclusion_reason VARCHAR(255) NULL,
  raw_values JSON NULL,
  imported_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_historical_cost_source_row (estate_id,source_file_id,source_sheet,source_row_number,source_item_key),
  KEY ix_historical_cost_year (estate_id,record_year,included_in_totals),
  KEY ix_historical_cost_actor (estate_id,actor_name,record_year),
  CONSTRAINT fk_historical_cost_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_historical_cost_duplicate FOREIGN KEY (duplicate_of) REFERENCES historical_cost_records(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
