CREATE TABLE IF NOT EXISTS hospitality_inquiries (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  intake_item_id CHAR(36) NULL,
  status ENUM('new','responded','converted','closed','spam') NOT NULL DEFAULT 'new',
  subject VARCHAR(300) NULL,
  sender_name VARCHAR(180) NULL,
  sender_address VARCHAR(255) NULL,
  received_at DATETIME(6) NOT NULL,
  message_text MEDIUMTEXT NULL,
  response_subject VARCHAR(300) NULL,
  response_body MEDIUMTEXT NULL,
  responded_at DATETIME(6) NULL,
  responded_by VARCHAR(180) NULL,
  reservation_id CHAR(36) NULL,
  internal_notes TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_hospitality_inquiry_intake (estate_id,intake_item_id),
  KEY idx_hospitality_inquiry_queue (estate_id,status,received_at),
  CONSTRAINT fk_hospitality_inquiry_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_hospitality_inquiry_intake FOREIGN KEY (intake_item_id) REFERENCES intake_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_hospitality_inquiry_reservation FOREIGN KEY (reservation_id) REFERENCES hospitality_reservations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
