CREATE TABLE IF NOT EXISTS register_catalog_items (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  source_type ENUM('fattureincloud','hospitality','manual') NOT NULL,
  external_id VARCHAR(190) NULL,
  name VARCHAR(220) NOT NULL,
  sku VARCHAR(100) NULL,
  description TEXT NULL,
  category VARCHAR(120) NULL,
  unit VARCHAR(40) NOT NULL DEFAULT 'each',
  gross_price_eur DECIMAL(16,4) NOT NULL DEFAULT 0,
  net_price_eur DECIMAL(16,4) NOT NULL DEFAULT 0,
  vat_rate DECIMAL(7,4) NOT NULL DEFAULT 0,
  fic_vat_id BIGINT NULL,
  track_stock TINYINT(1) NOT NULL DEFAULT 0,
  source_stock_quantity DECIMAL(16,3) NULL,
  source_stock_updated_at DATETIME(6) NULL,
  sellable TINYINT(1) NOT NULL DEFAULT 1,
  price_editable TINYINT(1) NOT NULL DEFAULT 0,
  display_order INT NOT NULL DEFAULT 100,
  source_payload JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_register_catalog_source (estate_id,source_type,external_id),
  KEY ix_register_catalog_sellable (estate_id,sellable,source_type,display_order),
  CONSTRAINT fk_register_catalog_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS register_sales (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  receipt_number VARCHAR(80) NOT NULL,
  status ENUM('draft','awaiting_payment','paid','void','refunded','payment_review') NOT NULL DEFAULT 'draft',
  payment_method ENUM('cash','paypal','paypal_pos','other') NULL,
  payment_status ENUM('unpaid','pending','paid','refunded','failed','review') NOT NULL DEFAULT 'unpaid',
  discount_eur DECIMAL(16,2) NOT NULL DEFAULT 0,
  subtotal_eur DECIMAL(16,2) NOT NULL DEFAULT 0,
  vat_eur DECIMAL(16,2) NOT NULL DEFAULT 0,
  total_eur DECIMAL(16,2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'EUR',
  paypal_account ENUM('us','it') NOT NULL DEFAULT 'us',
  checkout_language ENUM('en','it') NOT NULL DEFAULT 'en',
  tender_total DECIMAL(16,2) NOT NULL DEFAULT 0,
  usd_per_eur DECIMAL(16,6) NULL,
  customer_name VARCHAR(220) NULL,
  customer_email VARCHAR(190) NULL,
  hospitality_reservation_id CHAR(36) NULL,
  notes TEXT NULL,
  paypal_order_id VARCHAR(120) NULL,
  paypal_capture_id VARCHAR(120) NULL,
  paypal_status VARCHAR(80) NULL,
  terminal_reference VARCHAR(160) NULL,
  fic_sync_status ENUM('not_required','pending','posted','failed') NOT NULL DEFAULT 'not_required',
  fic_receipt_id VARCHAR(190) NULL,
  fic_last_error TEXT NULL,
  print_count INT UNSIGNED NOT NULL DEFAULT 0,
  created_by VARCHAR(190) NOT NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_register_receipt (estate_id,receipt_number),
  UNIQUE KEY uq_register_paypal_order (paypal_order_id),
  KEY ix_register_sales_status (estate_id,status,created_at),
  CONSTRAINT fk_register_sale_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_register_sale_reservation FOREIGN KEY (hospitality_reservation_id) REFERENCES hospitality_reservations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS register_sale_items (
  id CHAR(36) PRIMARY KEY,
  sale_id CHAR(36) NOT NULL,
  line_number SMALLINT UNSIGNED NOT NULL,
  catalog_item_id CHAR(36) NULL,
  source_type ENUM('fattureincloud','hospitality','manual') NOT NULL,
  external_id VARCHAR(190) NULL,
  item_name VARCHAR(220) NOT NULL,
  sku VARCHAR(100) NULL,
  unit VARCHAR(40) NOT NULL DEFAULT 'each',
  quantity DECIMAL(16,3) NOT NULL,
  unit_gross_eur DECIMAL(16,4) NOT NULL,
  discount_percent DECIMAL(7,3) NOT NULL DEFAULT 0,
  vat_rate DECIMAL(7,4) NOT NULL DEFAULT 0,
  line_gross_eur DECIMAL(16,2) NOT NULL,
  line_vat_eur DECIMAL(16,2) NOT NULL DEFAULT 0,
  track_stock TINYINT(1) NOT NULL DEFAULT 0,
  inventory_posted_to_fic TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_register_sale_line (sale_id,line_number),
  KEY ix_register_sale_catalog (catalog_item_id),
  CONSTRAINT fk_register_item_sale FOREIGN KEY (sale_id) REFERENCES register_sales(id) ON DELETE CASCADE,
  CONSTRAINT fk_register_item_catalog FOREIGN KEY (catalog_item_id) REFERENCES register_catalog_items(id) ON DELETE SET NULL,
  CONSTRAINT ck_register_item_quantity CHECK (quantity > 0),
  CONSTRAINT ck_register_item_price CHECK (unit_gross_eur >= 0),
  CONSTRAINT ck_register_item_discount CHECK (discount_percent >= 0 AND discount_percent <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO app_settings (estate_id,setting_key,setting_value)
SELECT id,'register_settings',JSON_OBJECT(
  'store_name','Azienda Agricola Tenuta Baiamonte S.S.',
  'receipt_header','Tenuta Baiamonte',
  'receipt_footer','Grazie · Thank you',
  'receipt_note','Operational receipt · not a fiscal document',
  'default_vat_rate',22,
  'usd_per_eur',1.1567,
  'exchange_rate_date','2026-08-14',
  'exchange_rate_source','ECB reference rate; editable checkout rate',
  'allow_cash',true,
  'allow_paypal_pos',true
) FROM estates
ON DUPLICATE KEY UPDATE setting_value=setting_value;
