ALTER TABLE lab_samples
  ADD COLUMN source_sample_name VARCHAR(180) NULL AFTER sample_name,
  ADD COLUMN canonical_sample_name VARCHAR(180) NULL AFTER source_sample_name,
  ADD KEY ix_lab_sample_canonical_vintage (estate_id,canonical_sample_name,vintage_year,lab_date);

CREATE TABLE IF NOT EXISTS lab_learning_cases (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  cutoff_result_id CHAR(36) NOT NULL,
  cutoff_sample_id CHAR(36) NOT NULL,
  cutoff_date DATE NOT NULL,
  vintage_year SMALLINT UNSIGNED NOT NULL,
  canonical_sample_name VARCHAR(180) NOT NULL,
  sample_type VARCHAR(40) NOT NULL,
  process_stage VARCHAR(80) NOT NULL,
  analyte_code VARCHAR(80) NOT NULL,
  unit VARCHAR(50) NOT NULL,
  series_key VARCHAR(600) NOT NULL,
  input_signature CHAR(64) NOT NULL,
  input_snapshot JSON NOT NULL,
  projection_value DECIMAL(18,8) NULL,
  projection_date DATE NULL,
  projection_method VARCHAR(80) NOT NULL,
  projection_confidence VARCHAR(40) NOT NULL,
  current_result_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  prior_vintage_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  feature_schema_version VARCHAR(80) NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  learning_status VARCHAR(40) NOT NULL,
  learned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_lab_learning_cutoff_result (cutoff_result_id),
  KEY ix_lab_learning_series (estate_id,canonical_sample_name,sample_type,analyte_code,vintage_year,cutoff_date),
  KEY ix_lab_learning_status (estate_id,learning_status,cutoff_date),
  CONSTRAINT fk_lab_learning_case_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_lab_learning_case_result FOREIGN KEY (cutoff_result_id) REFERENCES lab_results(id) ON DELETE CASCADE,
  CONSTRAINT fk_lab_learning_case_sample FOREIGN KEY (cutoff_sample_id) REFERENCES lab_samples(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lab_learning_outcomes (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  learning_case_id CHAR(36) NOT NULL,
  actual_result_id CHAR(36) NOT NULL,
  actual_sample_id CHAR(36) NOT NULL,
  actual_date DATE NOT NULL,
  actual_value DECIMAL(18,8) NOT NULL,
  forecast_horizon_days SMALLINT UNSIGNED NOT NULL,
  signed_error DECIMAL(18,8) NULL,
  absolute_error DECIMAL(18,8) NULL,
  absolute_percentage_error DECIMAL(12,5) NULL,
  direction_correct TINYINT(1) NULL,
  outcome_status VARCHAR(40) NOT NULL,
  outcome_summary TEXT NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  learned_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_lab_learning_outcome_case (learning_case_id),
  KEY ix_lab_learning_outcome_date (estate_id,actual_date,outcome_status),
  CONSTRAINT fk_lab_learning_outcome_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_lab_learning_outcome_case FOREIGN KEY (learning_case_id) REFERENCES lab_learning_cases(id) ON DELETE CASCADE,
  CONSTRAINT fk_lab_learning_outcome_result FOREIGN KEY (actual_result_id) REFERENCES lab_results(id) ON DELETE CASCADE,
  CONSTRAINT fk_lab_learning_outcome_sample FOREIGN KEY (actual_sample_id) REFERENCES lab_samples(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS lab_learning_models (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  model_version VARCHAR(80) NOT NULL,
  feature_schema_version VARCHAR(80) NOT NULL,
  trained_at DATETIME(6) NOT NULL,
  data_through DATE NULL,
  normalized_sample_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  numeric_result_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  projection_case_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  observed_outcome_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  represented_vintage_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  model_status VARCHAR(40) NOT NULL,
  parameters_snapshot JSON NOT NULL,
  validation_metrics JSON NOT NULL,
  data_quality_snapshot JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_lab_learning_model_version (estate_id,model_version),
  KEY ix_lab_learning_model_current (estate_id,trained_at),
  CONSTRAINT fk_lab_learning_model_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
