CREATE TABLE IF NOT EXISTS camera_security_events (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  source_key VARCHAR(190) NOT NULL,
  camera_entity_id VARCHAR(255) NOT NULL,
  camera_name VARCHAR(180) NOT NULL,
  area VARCHAR(80) NOT NULL DEFAULT 'estate',
  event_type VARCHAR(80) NOT NULL,
  severity ENUM('info','warning','critical') NOT NULL DEFAULT 'info',
  detected_at DATETIME(6) NOT NULL,
  last_seen_at DATETIME(6) NOT NULL,
  ended_at DATETIME(6) NULL,
  review_status ENUM('new','reviewed','dismissed') NOT NULL DEFAULT 'new',
  reviewed_by VARCHAR(160) NULL,
  reviewed_at DATETIME(6) NULL,
  evidence_url VARCHAR(500) NULL,
  linked_type VARCHAR(80) NULL,
  linked_id VARCHAR(100) NULL,
  metadata JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_camera_security_source (estate_id, source_key),
  KEY ix_camera_security_recent (estate_id, detected_at),
  KEY ix_camera_security_review (estate_id, review_status, detected_at),
  KEY ix_camera_security_active (estate_id, event_type, ended_at),
  CONSTRAINT fk_camera_security_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
