CREATE TABLE IF NOT EXISTS wildlife_observations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  estate_id CHAR(36) NOT NULL,
  camera_entity_id VARCHAR(255) NOT NULL,
  camera_name VARCHAR(180) NOT NULL,
  observed_at DATETIME(6) NOT NULL,
  species ENUM('fox','likely_fox','dog','cat','other','uncertain') NOT NULL DEFAULT 'uncertain',
  fox_visible TINYINT(1) NOT NULL DEFAULT 0,
  confidence_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
  activity ENUM('walking','feeding','sniffing','running','standing','lying','unknown') NOT NULL DEFAULT 'unknown',
  grape_risk ENUM('none','low','moderate','high','unknown') NOT NULL DEFAULT 'unknown',
  night_observation TINYINT(1) NOT NULL DEFAULT 0,
  frame_sha256 CHAR(64) NOT NULL,
  evidence_id CHAR(64) NULL,
  review_status ENUM('unreviewed','confirmed','rejected') NOT NULL DEFAULT 'unreviewed',
  notification_status VARCHAR(80) NOT NULL DEFAULT 'not_requested',
  notified_at DATETIME(6) NULL,
  model_version VARCHAR(120) NULL,
  evidence JSON NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  UNIQUE KEY uq_wildlife_frame (estate_id,camera_entity_id,frame_sha256),
  KEY ix_wildlife_species_time (estate_id,species,observed_at),
  KEY ix_wildlife_review (estate_id,review_status,observed_at),
  CONSTRAINT fk_wildlife_observation_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
