-- Owner-confirmed 2026 cellar purchases. Product labels are evidence of stock,
-- not authority to dose; official technical sheets and laboratory gates govern.
CREATE TABLE IF NOT EXISTS enology_product_stock (
  id CHAR(36) PRIMARY KEY,
  estate_id CHAR(36) NOT NULL,
  product_catalog_id CHAR(36) NOT NULL,
  stock_key VARCHAR(180) NOT NULL,
  supplier_name VARCHAR(160) NULL,
  product_lot VARCHAR(120) NULL,
  expires_on DATE NULL,
  package_size DECIMAL(12,4) NULL,
  package_unit VARCHAR(30) NULL,
  minimum_package_count INT NOT NULL DEFAULT 1,
  quantity_status ENUM('counted','minimum_visible','unverified') NOT NULL DEFAULT 'unverified',
  evidence_reference VARCHAR(255) NOT NULL,
  notes TEXT NULL,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_enology_product_stock (estate_id,product_catalog_id,stock_key),
  KEY ix_enology_product_stock_active (estate_id,active,expires_on),
  CONSTRAINT fk_enology_product_stock_estate FOREIGN KEY (estate_id) REFERENCES estates(id) ON DELETE CASCADE,
  CONSTRAINT fk_enology_product_stock_product FOREIGN KEY (product_catalog_id) REFERENCES enology_product_catalog(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE enology_product_protocols ADD COLUMN IF NOT EXISTS required_lab_analytes VARCHAR(255) NULL AFTER prerequisites;
ALTER TABLE enology_product_protocols ADD COLUMN IF NOT EXISTS lab_max_age_days INT NULL AFTER required_lab_analytes;

INSERT INTO enology_product_catalog
  (id,manufacturer,product_name,normalized_name,range_code,range_name,product_class,wine_colors,process_stages,description,product_url,pds_url,dose_min,dose_max,dose_unit,dose_basis,dose_verified,source_url,source_checked_at,present_in_latest)
VALUES
  (UUID(),'ENARTIS','CLARIL AF','claril af','fining','Fining agents','fining','any','must,clarification,aging','Bentonite, PVPP and pea-protein fining aid for clarification, oxidation/pinking control and protein stability.','https://shop-usa.enartis.com/claril-af-1','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ClarilAf.pdf',30,150,'g/hL','Purpose-specific official ranges; a recorded laboratory bench trial must select the exact rate.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ClarilAf.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisTan ROUGE','enartistan rouge','tannins','Tannins','tannin','red,rose','receiving,must,fermentation,aging','Blend of condensed and hydrolysable tannins for red/rose color and protein stabilization.','https://shop-usa.enartis.com/enartis-tan-rouge-2','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanRouge.pdf',100,200,'g/ton','Official must range for sound fruit; mold-affected fruit and finished wine have separate protocols.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanRouge.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisPro BLANCO','enartispro blanco','yeast_derivatives','Yeast derivatives','yeast_derivative','white,rose','pre-fermentation,fermentation','Inactivated yeast rich in soluble mannoproteins for antioxidant protection, mouthfeel, and stability in white and rose wine.','https://shop-usa.enartis.com/enartis-pro-blanco','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProBlanco.pdf',10,15,'g/hL','Official range for young white/rose wine; wines held longer than six months use a separate 20-30 g/hL review.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProBlanco.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisFerm ES181','enartisferm es181','yeast','Yeast','yeast','white','must,pre-fermentation','Saccharomyces yeast for varietal white wines and low-temperature or reductive fermentation.','https://shop-usa.enartis.com/enartisferm-es181','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-FermEs181.pdf',20,40,'g/hL','Official product data sheet; exact rate depends on sugar, fruit condition and microbiological difficulty.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-FermEs181.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisFerm D20','enartisferm d20','yeast','Yeast','yeast','red','must,pre-fermentation','Saccharomyces yeast for red varieties, high potential alcohol and/or high-temperature fermentation.','https://shop-usa.enartis.com/enartis-ferm-d20-2095','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-FermD20.pdf',20,40,'g/hL','Official product data sheet; exact rate depends on sugar, fruit condition and microbiological difficulty.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-FermD20.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisZym RS(P)','enartiszym rs p','enzymes','Enzymes','enzyme','white,rose','pressing,must','Pectolytic and hemicellulase enzyme for rapid settling or flotation of difficult-to-clarify juice after pressing.','https://shop-usa.enartis.com/enartis-zym-rs-p','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ZymRsP.pdf',1,3,'g/hL','Official product data sheet; choose within the range from grape variety, pH, temperature and process.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ZymRsP.pdf',NOW(6),1),
  (UUID(),'ENARTIS','NUTRIFERM SPECIAL','nutriferm special','nutrients','Nutrients','nutrient','any','fermentation','Ammonium phosphate, inactivated yeast and thiamine nutrient for measured fermentation need.','https://shop-usa.enartis.com/nutriferm-special','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-NutrifermSpecial.pdf',30,40,'g/hL','Official fermentation range; YAN/APA, potential alcohol, turbidity and total nutrient additions must be reviewed.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-NutrifermSpecial.pdf',NOW(6),1),
  (UUID(),'ENARTIS','NUTRIFERM NO STOP','nutriferm no stop','nutrients','Nutrients','nutrient','any','fermentation','Inactivated and autolyzed yeast with thiamine for prevention or correction of sluggish/stuck fermentation.','https://shop-usa.enartis.com/nutriferm-no-stop','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-NutrifermNoStop.pdf',20,40,'g/hL','Purpose-specific official rates; use only when fermentation trajectory and laboratory evidence support the selected protocol.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-NutrifermNoStop.pdf',NOW(6),1),
  (UUID(),'ENODORO','Acido L(+) Tartarico Naturale E334','acido l tartarico naturale e334','acids','Acidification','treatment','any','must,wine','Natural L(+)-tartaric acid for professional enological acidification. Exact treatment requires current pH/total acidity, bench trials, legal review and enologist approval.','https://www.enodoro.it/',NULL,NULL,NULL,NULL,'No default dose: calculate only from the enologist-selected bench-trial rate and verified lot volume.',0,'https://www.enodoro.it/',NOW(6),1)
ON DUPLICATE KEY UPDATE range_code=VALUES(range_code),range_name=VALUES(range_name),product_class=VALUES(product_class),wine_colors=VALUES(wine_colors),process_stages=VALUES(process_stages),description=VALUES(description),product_url=VALUES(product_url),pds_url=VALUES(pds_url),dose_min=VALUES(dose_min),dose_max=VALUES(dose_max),dose_unit=VALUES(dose_unit),dose_basis=VALUES(dose_basis),dose_verified=VALUES(dose_verified),source_url=VALUES(source_url),source_checked_at=VALUES(source_checked_at),present_in_latest=1,active=1;

INSERT INTO enology_product_protocols
  (id,product_catalog_id,protocol_code,protocol_name,purpose,wine_colors,process_stages,trigger_code,dose_min,dose_max,dose_unit,dose_basis,preparation,application_instructions,prerequisites,required_lab_analytes,lab_max_age_days,incompatibilities,minimum_contact_hours,source_url,source_revision,verified_on)
SELECT UUID(),p.id,x.protocol_code,x.protocol_name,x.purpose,x.wine_colors,x.process_stages,x.trigger_code,x.dose_min,x.dose_max,x.dose_unit,x.dose_basis,x.preparation,x.application_instructions,x.prerequisites,x.required_lab_analytes,x.lab_max_age_days,x.incompatibilities,x.minimum_contact_hours,x.source_url,x.source_revision,'2026-09-15'
FROM enology_product_catalog p
JOIN (
  SELECT 'enartisferm d20' product_key,'standard_inoculation' protocol_code,'Red-wine inoculation' protocol_name,'Controlled red-wine alcoholic fermentation' purpose,'red' wine_colors,'must,pre-fermentation' process_stages,'inoculation' trigger_code,20 dose_min,40 dose_max,'g/hL' dose_unit,'Official Enartis data sheet' dose_basis,'Suspend in 10 times its weight of clean water at 35-40 C; stir gently, rest 20 minutes, then stir again.' preparation,'Add while beginning to fill the fermenter and homogenize. Keep the yeast suspension and juice within 10 C.' application_instructions,'Verified liquid volume, must temperature, current chemistry, selected exact rate and enologist approval' prerequisites,'ph,total_acidity,potential_alcohol,yan' required_lab_analytes,7 lab_max_age_days,'Use the high end only for documented rotten fruit, high sugar or difficult microbiological conditions.' incompatibilities,NULL minimum_contact_hours,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-FermD20.pdf' source_url,'current sheet accessed 2026-09-15' source_revision
  UNION ALL SELECT 'enartisferm es181','standard_inoculation','White-wine inoculation','Varietal white-wine alcoholic fermentation','white','must,pre-fermentation','inoculation',20,40,'g/hL','Official Enartis data sheet','Suspend in 10 times its weight of clean water at 35-38 C; stir gently, rest 20 minutes, then stir again.','Add while beginning to fill the fermenter and homogenize. Keep the yeast suspension and juice within 10 C.','Verified liquid volume, must temperature, current chemistry, selected exact rate and enologist approval','ph,total_acidity,potential_alcohol,yan',7,'Low-temperature/reductive use requires a complete nutrition and fermentation-survival plan.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-FermEs181.pdf','revision 6 08/2025'
  UNION ALL SELECT 'enartiszym rs p','post_press_settling','Post-press juice settling','Rapid settling or flotation of difficult-to-clarify white/rose juice','white,rose','pressing,must','pressing',1,3,'g/hL','Official Enartis data sheet','Dissolve in 10 times its weight of water or juice.','Add uniformly to juice after pressing.','Verified juice volume, 8-30 C process temperature, pH at least 2.9, selected settling/flotation objective and enologist approval','ph,total_acidity,turbidity',3,'Avoid inhaling enzyme dust; follow the SDS and respiratory-protection instructions. Bentonite can inactivate pectolytic enzymes.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ZymRsP.pdf','current sheet accessed 2026-09-15'
  UNION ALL SELECT 'enartistan rouge','sound_must','Sound-fruit must color protection','Protein/color stabilization during red or rose must processing','red,rose','receiving,must,fermentation','crusher_or_fermentation',100,200,'g/ton','Official Enartis sound-fruit must range','Dissolve 1:10 in water, wine or must while continuously mixing.','Add uniformly during pump-over with a dosing pump or Venturi.','Recorded grape weight, sound-fruit assessment, current chemistry, phenolic objective and enologist approval','ph,total_acidity,potential_alcohol',7,'Mold-affected fruit uses a separate 150-400 g/ton protocol; do not select that range without recorded fruit condition.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanRouge.pdf','revision 2 June 2020'
  UNION ALL SELECT 'enartistan rouge','wine_bench_trial','Wine tannin bench trial','Color/protein stabilization during early maturation','red,rose','aging','bench_trial',5,15,'g/hL','Official Enartis wine range','Dissolve 1:10 in water, wine or must while continuously mixing.','After a recorded laboratory/sensory trial selects the rate, add uniformly during pump-over.','Verified wine volume, recorded bench-trial result, selected rate, stability review and enologist approval','ph,total_acidity',30,'Near bottling, verify filterability plus protein and colloidal stability; allow one to two weeks before bottling.',168,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanRouge.pdf','revision 2 June 2020'
  UNION ALL SELECT 'enartispro blanco','young_wine','Young white/rose mannoprotein program','Antioxidant protection, mouthfeel and stability for wine marketed young','white,rose','pre-fermentation,fermentation','inoculation',10,15,'g/hL','Official Enartis young-wine range','Disperse in 10 times its weight of water or must and mix until lump-free.','Add uniformly at the beginning of fermentation while filling or by pump-over.','Verified liquid volume, target release age under four months, current chemistry and enologist approval','ph,total_acidity,potential_alcohol',7,'Wines held over six months use a separate 20-30 g/hL review; do not silently substitute ranges.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProBlanco.pdf','current sheet accessed 2026-09-15'
  UNION ALL SELECT 'nutriferm special','first_third','First-third fermentation nutrition','Support a measured nutrition need during alcoholic fermentation','any','fermentation','density_drop_30',30,40,'g/hL','Official Enartis fermentation range','Dissolve in a small amount of water or must and wait 15-20 minutes.','Add at one-third fermentation after confirming the trajectory and total nutrient plan.','Verified liquid volume, linked current YAN/APA, potential alcohol, turbidity, density baseline/current reading, total nutrient accounting and enologist approval','yan,potential_alcohol,turbidity',7,'EU maximum 60 g/hL. Do not add merely because product is in stock or stack with other nitrogen sources without total accounting.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-NutrifermSpecial.pdf','current sheet accessed 2026-09-15'
  UNION ALL SELECT 'nutriferm no stop','sluggish_corrective','Sluggish/stuck fermentation correction','Correct a documented sluggish or stuck alcoholic fermentation','any','fermentation','sluggish_fermentation',40,40,'g/hL','Official Enartis corrective rate','Disperse in five times its weight of water or juice.','Add uniformly to must/wine before incorporating yeast acclimatized to alcohol.','Verified liquid volume, supported sluggish/stuck trajectory, current YAN/APA and volatile-acidity review, restart plan and enologist approval','yan,potential_alcohol,volatile_acidity',3,'EU/USA limit 40 g/hL. This corrective protocol is not a routine nutrient addition.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-NutrifermNoStop.pdf','current sheet accessed 2026-09-15'
  UNION ALL SELECT 'claril af','white_must_bench','White-must fining bench trial','Clarification and oxidation/pinking/protein-stability treatment','white','must,clarification','bench_trial',50,90,'g/hL','Official Enartis white-must range','Disperse 1:10 in water, homogenize and rest 3-6 hours.','After a recorded bench trial selects the exact rate, add during pump-over to at least half the volume using a Venturi or dosing pump.','Verified liquid volume, treatment objective, progressive laboratory bench trial and enologist approval','ph,total_acidity,turbidity,catechins',3,'Purpose-specific ranges are not interchangeable. This product contains bentonite, PVPP and pea protein.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ClarilAf.pdf','revision 7 May 2022'
  UNION ALL SELECT 'claril af','wine_bench','Wine fining bench trial','Clarification and oxidation/pinking/protein-stability treatment','any','wine,aging','bench_trial',30,80,'g/hL','Official Enartis wine range','Disperse 1:10 in water, homogenize and rest 3-6 hours.','After a recorded bench trial selects the exact rate, add during pump-over to at least half the volume using a Venturi or dosing pump.','Verified liquid volume, treatment objective, progressive laboratory bench trial and enologist approval','ph,total_acidity,turbidity,catechins',30,'Purpose-specific ranges are not interchangeable; assess stability and sensory outcome after the trial.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ClarilAf.pdf','revision 7 May 2022'
  UNION ALL SELECT 'acido l tartarico naturale e334','acidification_trial','Acidification bench-trial calculator','Correct acidity only from current chemistry and an approved trial rate','any','must,wine','acidification_bench_trial',NULL,NULL,NULL,'No manufacturer default dose recorded','Follow the current Enodoro technical/safety sheet; prepare the exact enologist-selected trial rate and dissolve completely.','Calculate total product only after the bench-trial rate is recorded: grams = selected g/L x verified lot liters. Add uniformly and retest.','Verified lot volume, linked current pH and total acidity, target defined by enologist, bench trial, legal-limit review and approval','ph,total_acidity',3,'No automatic dose. Potassium and tartrate-stability context must be reviewed where relevant.',NULL,'https://www.enodoro.it/','owner label photographed 2026-09-15; technical sheet required'
) x ON p.normalized_name=x.product_key AND p.manufacturer IN ('ENARTIS','ENODORO')
ON DUPLICATE KEY UPDATE protocol_name=VALUES(protocol_name),purpose=VALUES(purpose),wine_colors=VALUES(wine_colors),process_stages=VALUES(process_stages),trigger_code=VALUES(trigger_code),dose_min=VALUES(dose_min),dose_max=VALUES(dose_max),dose_unit=VALUES(dose_unit),dose_basis=VALUES(dose_basis),preparation=VALUES(preparation),application_instructions=VALUES(application_instructions),prerequisites=VALUES(prerequisites),required_lab_analytes=VALUES(required_lab_analytes),lab_max_age_days=VALUES(lab_max_age_days),incompatibilities=VALUES(incompatibilities),minimum_contact_hours=VALUES(minimum_contact_hours),source_url=VALUES(source_url),source_revision=VALUES(source_revision),verified_on=VALUES(verified_on),active=1;

-- Make the existing source-verified protocols participate in the same permanent lab gate.
UPDATE enology_product_protocols SET required_lab_analytes='ph,total_acidity,potential_alcohol,yan',lab_max_age_days=7 WHERE trigger_code='inoculation' AND required_lab_analytes IS NULL;
UPDATE enology_product_protocols SET required_lab_analytes='yan,potential_alcohol,turbidity',lab_max_age_days=7 WHERE trigger_code='density_drop_30' AND required_lab_analytes IS NULL;
UPDATE enology_product_protocols SET required_lab_analytes='ph,total_acidity,turbidity',lab_max_age_days=3 WHERE trigger_code='pressing' AND required_lab_analytes IS NULL;
UPDATE enology_product_protocols SET required_lab_analytes='ph,total_acidity,potential_alcohol',lab_max_age_days=7 WHERE trigger_code IN ('crusher_or_fermentation','pump_over','first_pump_over') AND required_lab_analytes IS NULL;
UPDATE enology_product_protocols SET required_lab_analytes='ph,total_acidity',lab_max_age_days=30 WHERE trigger_code='ageing_review' AND required_lab_analytes IS NULL;

INSERT INTO enology_product_stock
  (id,estate_id,product_catalog_id,stock_key,supplier_name,product_lot,expires_on,package_size,package_unit,minimum_package_count,quantity_status,evidence_reference,notes)
SELECT UUID(),e.id,p.id,x.stock_key,x.supplier_name,x.product_lot,x.expires_on,x.package_size,x.package_unit,x.minimum_package_count,'minimum_visible','Owner cellar product photographs 2026-09-15',x.notes
FROM estates e CROSS JOIN (
  SELECT 'ENARTIS' manufacturer,'claril af' product_key,'photo-2026-09-15-claril-af' stock_key,'Enartis' supplier_name,'1148296' product_lot,'2027-03-31' expires_on,1 package_size,'kg' package_unit,1 minimum_package_count,'One 1 kg bag visible; exact unopened/on-hand count should be confirmed.' notes
  UNION ALL SELECT 'ENARTIS','enartistan rouge','photo-2026-09-15-tan-rouge','Enartis',NULL,NULL,1,'kg',1,'At least one package visible; package size follows the pictured 1 kg format and must be confirmed at physical count.'
  UNION ALL SELECT 'ENARTIS','enartispro blanco','photo-2026-09-15-pro-blanco','Enartis','50882','2029-06-30',1,'kg',1,'One 1 kg bag visible.'
  UNION ALL SELECT 'ENARTIS','enartisferm es181','photo-2026-09-15-es181','Enartis',NULL,NULL,0.5,'kg',1,'At least one box visible; official package size is 0.5 kg. Confirm remaining sealed units.'
  UNION ALL SELECT 'ENARTIS','enartisferm d20','photo-2026-09-15-d20','Enartis',NULL,NULL,0.5,'kg',2,'At least two boxes visible; official package size is 0.5 kg. Confirm remaining sealed units.'
  UNION ALL SELECT 'ENARTIS','enartiszym rs p','photo-2026-09-15-zym-rsp','Enartis',NULL,NULL,100,'g',1,'At least one 100 g package visible. Enzyme dust respiratory warning applies.'
  UNION ALL SELECT 'ENARTIS','nutriferm special','photo-2026-09-15-nutriferm-special','Enartis',NULL,NULL,1,'kg',1,'At least one 1 kg bag visible; shelf count not asserted from the photograph.'
  UNION ALL SELECT 'ENARTIS','nutriferm no stop','photo-2026-09-15-nutriferm-no-stop','Enartis',NULL,NULL,1,'kg',1,'At least one 1 kg bag visible; shelf count not asserted from the photograph.'
  UNION ALL SELECT 'ENODORO','acido l tartarico naturale e334','photo-2026-09-15-tartaric-acid','Enodoro','B24X262401','2029-06-24',1,'kg',1,'One 1 kg bag visible. No dose is authorized from the label photograph.'
) x JOIN enology_product_catalog p ON p.manufacturer=x.manufacturer AND p.normalized_name=x.product_key
WHERE 1=1
ON DUPLICATE KEY UPDATE supplier_name=VALUES(supplier_name),product_lot=VALUES(product_lot),expires_on=VALUES(expires_on),package_size=VALUES(package_size),package_unit=VALUES(package_unit),minimum_package_count=VALUES(minimum_package_count),quantity_status=VALUES(quantity_status),evidence_reference=VALUES(evidence_reference),notes=VALUES(notes),active=1;
