-- Curated premium/specialist products from current official manufacturer pages
-- and technical sheets. Marketing rank claims are intentionally not stored.
INSERT INTO enology_product_catalog
  (id,manufacturer,product_name,normalized_name,range_code,range_name,product_class,wine_colors,process_stages,description,product_url,pds_url,dose_min,dose_max,dose_unit,dose_basis,dose_verified,source_url,source_checked_at,present_in_latest)
VALUES
  (UUID(),'LALLEMAND OENOLOGY','LALVIN ICV D254','lalvin icv d254','lalvin','Wine yeasts','yeast','red,white','must,pre-fermentation','Selected S. cerevisiae for red and barrel-fermented white wines; official sheet describes moderate nitrogen demand and 16% alcohol tolerance.','https://www.lallemandwine.com/it/italy/prodotti/lievito-di-vino/lalvin-icv-d254','https://products.lallemandwine.com/storage/files/wine-yeasts/4e97d7ea8863f8f9437ff57aa6fa3bacefde1c6e.pdf',20,40,'g/hL','Official Lallemand specification range; the technical application sheet uses 25 g/hL.',1,'https://www.lallemandwine.com/it/italy/prodotti/lievito-di-vino/lalvin-icv-d254',NOW(6),1),
  (UUID(),'LALLEMAND OENOLOGY','MANNOLEES','mannolees','yeast_derivatives','Specific yeast derivatives','yeast_derivative','any','aging,pre-bottling','Soluble yeast mannoprotein and vegetal-polysaccharide preparation for sensory and stability review before bottling.','https://www.lallemandwine.com/it/italy/prodotti/derivati-specifici-di-lievito/mannolees/','https://products.lallemandwine.com/storage/files/specific-yeast-derivatives/72-technical-datasheet-ce-1717485980.pdf',5,30,'g/hL','Official technical sheet; bench trials determine the rate for the wine matrix.',1,'https://products.lallemandwine.com/storage/files/specific-yeast-derivatives/72-technical-datasheet-ce-1717485980.pdf',NOW(6),1),
  (UUID(),'LALLEMAND OENOLOGY','MANNOSTYLE','mannostyle','yeast_derivatives','Specific yeast derivatives','yeast_derivative','any','pre-bottling','Soluble specific yeast mannoproteins and arabic gum for pre-bottling sensory review.','https://www.lallemandwine.com/en/new-zealand/products/specific-yeast-derivatives/','https://products.lallemandwine.com/storage/files/specific-yeast-derivatives/79-technical-datasheet-cp-1711531515.pdf',5,25,'g/hL','Official January 2024 technical sheet.',1,'https://products.lallemandwine.com/storage/files/specific-yeast-derivatives/79-technical-datasheet-cp-1711531515.pdf',NOW(6),1),
  (UUID(),'LALLEMAND OENOLOGY','LALVIN VP41','lalvin vp41','wine_bacteria','Wine bacteria','bacteria','red,white','fermentation,post-fermentation','Oenococcus oeni culture for malolactic fermentation; exact sachet coverage is printed on the selected pack.','https://www.lallemandwine.com/it/italy/prodotti/batteri-del-vino/lalvin-vp41','https://admin.lallemandwine.com/wp-content/uploads/2023/10/TDS_LALVIN-VP41_2022.pdf',NULL,NULL,NULL,'Use one sachet for the hL coverage printed on the pack; do not convert it to a mass rate.',0,'https://www.lallemandwine.com/it/italy/prodotti/batteri-del-vino/lalvin-vp41',NOW(6),1),

  (UUID(),'PERDOMINI-IOC','IOC DYNAMIX','ioc dynamix','ioc_yeasts','IOC yeasts','yeast','red','must,pre-fermentation','Blend of five S. cerevisiae strains for controlled red-wine alcoholic fermentation.','https://www.perdomini-ioc.com/en/oenological-products/ioc-range/','https://www.perdomini-ioc.com/wp-content/uploads/2019/06/FT-LEVURE-IOC-DYNAMIX-EN-rev-01-2024.pdf',20,30,'g/hL','Official IOC technical sheet revision 11-01-2024.',1,'https://www.perdomini-ioc.com/wp-content/uploads/2019/06/FT-LEVURE-IOC-DYNAMIX-EN-rev-01-2024.pdf',NOW(6),1),
  (UUID(),'PERDOMINI-IOC','IOC 18-2007','ioc 18 2007','bubble_art','Traditional method','yeast','white,rose','tirage','Selected yeast listed by IOC for pied-de-cuve preparation in traditional-method sparkling production.','https://www.perdomini-ioc.com/en/traditional-method/',NULL,10,10,'g/hL','Official IOC traditional-method program; local-agent pied-de-cuve protocol remains required.',1,'https://www.perdomini-ioc.com/en/traditional-method/',NOW(6),1),
  (UUID(),'PERDOMINI-IOC','Hydra PC','hydra pc','bubble_art','Traditional method','nutrient','white,rose','tirage','Yeast protector listed by IOC for tirage, including very low-pH base wines.','https://www.perdomini-ioc.com/en/traditional-method/',NULL,10,10,'g/hL','Official IOC traditional-method program.',1,'https://www.perdomini-ioc.com/en/traditional-method/',NOW(6),1),
  (UUID(),'PERDOMINI-IOC','Phosphate Titrés','phosphate titres','bubble_art','Traditional method','nutrient','white,rose','tirage','Nitrogen- and thiamine-based fermentation optimiser listed by IOC for tirage preparation.','https://www.perdomini-ioc.com/en/traditional-method/',NULL,5,5,'g/hL','Official IOC traditional-method program; total nutrient accounting is required.',1,'https://www.perdomini-ioc.com/en/traditional-method/',NOW(6),1),

  (UUID(),'OENOBRANDS','Fermivin MT48','fermivin mt48','fermivin','Wine yeasts','yeast','red','must,pre-fermentation','S. cerevisiae strain 4882 selected and validated for red wines; official page lists low nutrient demand and 15% alcohol tolerance.','https://oenobrands.com/product/yeast/fermivin-yeast/fermivin-mt48/',NULL,20,20,'g/hL','Official Oenobrands product page.',1,'https://oenobrands.com/product/yeast/fermivin-yeast/fermivin-mt48/',NOW(6),1),
  (UUID(),'OENOBRANDS','Rapidase Clear','rapidase clear','rapidase','Enzymes','enzyme','white,rose','pressing,must,clarification','Pectolytic enzyme for must clarification; the applicable rate varies with temperature and settling time.','https://oenobrands.com/product/enzyme/rapidase/clear/',NULL,1,2.5,'g/hL','Official temperature-dependent Oenobrands ranges; the protocol must select the applicable subrange.',1,'https://oenobrands.com/product/enzyme/rapidase/clear/',NOW(6),1),
  (UUID(),'OENOBRANDS','Rapidase Extra Color','rapidase extra color','rapidase','Enzymes','enzyme','red','receiving,maceration','Pectolytic enzyme for red-grape colour and polyphenol extraction.','https://oenobrands.com/product/enzyme/rapidase/extra-color/',NULL,2,3,'g/100kg','Official Oenobrands range at 22-28 C.',1,'https://oenobrands.com/product/enzyme/rapidase/extra-color/',NOW(6),1),
  (UUID(),'OENOBRANDS','Rapidase Batonnage','rapidase batonnage','rapidase','Enzymes','enzyme','red,white','aging','Beta-glucanase enzyme for accelerated release from wine lees during batonnage.','https://oenobrands.com/product/enzyme/rapidase/rapidase-batonnage/',NULL,2,2.5,'g/hL','Official temperature-dependent Oenobrands range with at least four weeks contact.',1,'https://oenobrands.com/product/enzyme/rapidase/rapidase-batonnage/',NOW(6),1),
  (UUID(),'OENOBRANDS','Final touch GUSTO','final touch gusto','final_touch','Mannoproteins','yeast_derivative','red','aging,pre-bottling','Liquid yeast mannoprotein fraction for red-wine texture and tartrate-stability review. Contains sulfites.','https://oenobrands.com/product/mannoprotein/final-touch/gusto/',NULL,10,40,'mL/hL','Official Oenobrands product page; stability tests are required beforehand.',1,'https://oenobrands.com/product/mannoprotein/final-touch/gusto/',NOW(6),1),
  (UUID(),'OENOBRANDS','Extraferm D''tox','extraferm d tox','feel_safe','Yeast derivatives','yeast_derivative','any','must,fermentation,wine','Yeast-cell-wall preparation with distinct preventative, stuck-fermentation and contaminant protocols.','https://oenobrands.com/product/yeast-derivate/feel-safe/extraferm-dtox/',NULL,20,40,'g/hL','Official purpose-specific Oenobrands rates; protocols are not interchangeable.',1,'https://oenobrands.com/product/yeast-derivate/feel-safe/extraferm-dtox/',NOW(6),1),
  (UUID(),'OENOBRANDS','Anchor Nourish','anchor nourish','anchor_nutrients','Nutrients','nutrient','any','fermentation','Inactivated yeast, DAP and thiamine nutrient for a measured fermentation nutrition plan.','https://oenobrands.com/product/yeast-derivate/anchor-nutrients/nourish/','https://oenobrands.com/wp-content/uploads/2024/07/Technical-data-sheet-Anchor-nutrient-Nourish_Eng_202107_Web.pdf',20,40,'g/hL','Official Oenobrands/Anchor range; total YAN accounting is required.',1,'https://oenobrands.com/product/yeast-derivate/anchor-nutrients/nourish/',NOW(6),1),

  (UUID(),'ENARTIS','EnartisTan MEL','enartistan mel','premium_tannins','Premium tannins','tannin','red,white,rose','aging','Liquid French-oak ellagic tannin preparation for purpose-specific aging and stabilization trials.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanMel.pdf',1,30,'mL/hL','Official color-specific range; white maximum 20 mL/hL, red maximum 30 mL/hL.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanMel.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisTan CLAR','enartistan clar','premium_tannins','Premium tannins','tannin','red,white','clarification,aging','Hydrolysable ellagitannin with separate juice-clarification, white-wine and red-wine rates.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanClar.pdf',3,10,'g/hL','Official purpose/color-specific ranges; a lab trial selects the exact protocol.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanClar.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisTan SKIN','enartistan skin','premium_tannins','Premium tannins','tannin','any','aging','Grape tannin for a purpose-specific finishing bench trial.','https://www.enartis.com/en-us/products/wine/tannins-en-us/grape-tannins-en-us/enartistan-skin/',NULL,3,20,'g/hL','Official Enartis product page; bench trial and current sheet govern the rate.',1,'https://www.enartis.com/en-us/products/wine/tannins-en-us/grape-tannins-en-us/enartistan-skin/',NOW(6),1),
  (UUID(),'ENARTIS','EnartisStab CLK+','enartisstab clk','stability','Stabilization','stabilizer','any','pre-bottling','Mannoprotein and potassium-polyaspartate preparation for tartrate-stability treatment review.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-StabClk.pdf',5,15,'g/hL','Official technical sheet; progressive trials, cold/minicontact test and filterability review determine the rate.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-StabClk.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisPro Q','enartispro q','microbiological_control','Microbiological control','treatment','any','must,fermentation','Activated chitosan and yeast-hull preparation for a supported microbiological-control objective.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProQ.pdf',10,30,'g/hL','Official Enartis microbiological-stabilization guidance; microbiological evidence is required.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProQ.pdf',NOW(6),1)
ON DUPLICATE KEY UPDATE range_code=VALUES(range_code),range_name=VALUES(range_name),product_class=VALUES(product_class),wine_colors=VALUES(wine_colors),process_stages=VALUES(process_stages),description=VALUES(description),product_url=VALUES(product_url),pds_url=VALUES(pds_url),dose_min=VALUES(dose_min),dose_max=VALUES(dose_max),dose_unit=VALUES(dose_unit),dose_basis=VALUES(dose_basis),dose_verified=VALUES(dose_verified),source_url=VALUES(source_url),source_checked_at=VALUES(source_checked_at),present_in_latest=1,active=1;

INSERT INTO enology_product_protocols
  (id,product_catalog_id,protocol_code,protocol_name,purpose,wine_colors,process_stages,trigger_code,dose_min,dose_max,dose_unit,dose_basis,preparation,application_instructions,prerequisites,required_lab_analytes,lab_max_age_days,incompatibilities,minimum_contact_hours,source_url,source_revision,verified_on)
SELECT UUID(),p.id,x.protocol_code,x.protocol_name,x.purpose,x.wine_colors,x.process_stages,x.trigger_code,x.dose_min,x.dose_max,x.dose_unit,x.dose_basis,x.preparation,x.application_instructions,x.prerequisites,x.required_lab_analytes,x.lab_max_age_days,x.incompatibilities,x.minimum_contact_hours,p.source_url,x.source_revision,'2026-09-15'
FROM enology_product_catalog p JOIN (
  SELECT 'LALLEMAND OENOLOGY' manufacturer,'lalvin icv d254' product_key,'standard_inoculation' protocol_code,'ICV D254 inoculation' protocol_name,'Controlled alcoholic fermentation' purpose,'red,white' wine_colors,'must,pre-fermentation' process_stages,'inoculation' trigger_code,20 dose_min,40 dose_max,'g/hL' dose_unit,'Official specification range' dose_basis,'Rehydrate with the current Lallemand yeast-protector protocol; the application sheet uses 40-43 C water and a 20 minute stand.' preparation,'Acclimatize gradually and keep the yeast suspension within 5-10 C of must; complete rehydration within 30 minutes.' application_instructions,'Verified volume, must temperature, current chemistry, nutrition plan and enologist strain/rate approval' prerequisites,'ph,total_acidity,potential_alcohol,yan' required_lab_analytes,7 lab_max_age_days,'Do not treat strain descriptions as proof of suitability for this lot.' incompatibilities,NULL minimum_contact_hours,'Lallemand application sheet version 3.2 / 11.2020' source_revision
  UNION ALL SELECT 'LALLEMAND OENOLOGY','mannolees','pre_bottling_trial','MANNOLEES bench trial','Pre-bottling sensory and stability trial','any','aging,pre-bottling','pre_bottling_bench',5,30,'g/hL','Official technical sheet','Suspend in ten times its weight of water or wine and mix.','After the recorded trial selects a rate, add uniformly and complete protein, tartrate and filterability checks.','Verified volume, sensory bench trial, protein/tartrate stability and enologist approval','ph,total_acidity,potassium',30,'Ingredient-label review may apply to mannoproteins and arabic gum under current rules.',24,'Lallemand technical sheet accessed 2026-09-15'
  UNION ALL SELECT 'LALLEMAND OENOLOGY','mannostyle','pre_bottling_trial','MANNOSTYLE bench trial','Pre-bottling sensory trial','any','pre-bottling','pre_bottling_bench',5,25,'g/hL','Official January 2024 technical sheet','Suspend in ten times its weight in water or must.','Add within 24 hours before pre-bottling filtration after a recorded trial and mix properly.','Verified volume, sensory/stability trial, filtration plan and enologist approval','ph,total_acidity,potassium',30,'Ingredient-label and filterability review required.',24,'January 2024 technical sheet'
  UNION ALL SELECT 'LALLEMAND OENOLOGY','lalvin vp41','direct_mlf','VP41 malolactic inoculation','Controlled malolactic fermentation','red,white','fermentation,post-fermentation','mlf_inoculation',NULL,NULL,NULL,'One sachet for the hL quantity printed on the selected pack','Use the exact current pack instructions; optional rehydration is in 20 times its weight of chlorine-free water at 20 C for no more than 15 minutes.','Distribute gently and monitor malic-acid degradation every 2-4 days; stabilize only after completion is confirmed.','Exact pack coverage, verified wine volume, MLF feasibility review and enologist approval','ph,malic_acid,total_so2,potential_alcohol',3,'Confirm temperature, molecular/free SO2, alcohol, nutrient status and no incompatible antimicrobial treatment.',NULL,'Lallemand VP41 sheet accessed 2026-09-15'

  UNION ALL SELECT 'PERDOMINI-IOC','ioc dynamix','standard_inoculation','IOC DYNAMIX inoculation','Controlled red-wine alcoholic fermentation','red','must,pre-fermentation','inoculation',20,30,'g/hL','Official IOC sheet revision 11-01-2024','Rehydrate in ten times its water volume at 37 C, mix gently and stand 20 minutes.','Acclimatize gradually; keep within 10 C of must and complete rehydration within 45 minutes.','Verified volume, temperature, current chemistry, nutrition plan and enologist approval','ph,total_acidity,potential_alcohol,yan',7,'For potential alcohol above 14%, official sheet says avoid fermentation temperature above 26 C.',NULL,'revision 11-01-2024'
  UNION ALL SELECT 'PERDOMINI-IOC','ioc 18 2007','traditional_method','IOC 18-2007 pied de cuve','Traditional-method pied-de-cuve yeast','white,rose','tirage','tirage',10,10,'g/hL','Official IOC Bubble Art program','Use the current IOC/local-agent pied-de-cuve preparation protocol.','Apply only within an approved tirage plan for the measured base-wine volume.','Verified base-wine volume, tirage plan, chemistry, pressure-rated process and enologist approval','ph,residual_sugar,free_so2,total_so2',3,'Not a still-wine primary-fermentation substitution.',NULL,'IOC traditional-method page accessed 2026-09-15'
  UNION ALL SELECT 'PERDOMINI-IOC','hydra pc','traditional_method','Hydra PC tirage protector','Yeast protection during tirage','white,rose','tirage','tirage',10,10,'g/hL','Official IOC Bubble Art program','Follow the current IOC/local-agent tirage preparation protocol.','Use only in the approved pied-de-cuve/tirage recipe.','Verified base-wine volume, tirage plan and enologist approval','ph,residual_sugar,free_so2,total_so2',3,'Especially relevant to very low pH; does not replace feasibility review.',NULL,'IOC traditional-method page accessed 2026-09-15'
  UNION ALL SELECT 'PERDOMINI-IOC','phosphate titres','traditional_method','Phosphate Titrés tirage nutrient','Fermentation optimisation during tirage','white,rose','tirage','tirage',5,5,'g/hL','Official IOC Bubble Art program','Follow the current IOC/local-agent tirage preparation protocol.','Use only after total nutrient and legal accounting in the approved tirage recipe.','Verified base-wine volume, tirage plan, YAN/nutrient accounting and enologist approval','yan,residual_sugar,free_so2,total_so2',3,'Contains nitrogen and thiamine; do not stack without total accounting.',NULL,'IOC traditional-method page accessed 2026-09-15'

  UNION ALL SELECT 'OENOBRANDS','fermivin mt48','standard_inoculation','Fermivin MT48 inoculation','Controlled red-wine alcoholic fermentation','red','must,pre-fermentation','inoculation',20,20,'g/hL','Official Oenobrands product page','Follow the current application data sheet for rehydration.','Add only after strain suitability, temperature and nutrition review.','Verified volume, current chemistry, temperature, nutrition plan and enologist approval','ph,total_acidity,potential_alcohol,yan',7,'Official page lists 20-30 C and 15% alcohol tolerance.',NULL,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','rapidase clear','must_clarification','Rapidase Clear clarification','Must depectinization and clarification','white,rose','pressing,must,clarification','must_clarification',1,2.5,'g/hL','Official temperature/settling-time ranges','Dilute ten times before addition.','Add as early as possible at crusher, press or after pressing; confirm completion with a pectin test.','Verified must volume, temperature, turbidity, pectin-test plan and enologist approval','ph,total_acidity,turbidity',3,'Bentonite removes/inactivates the enzyme; difficult cold settling has a separate product/rate.',NULL,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','rapidase extra color','red_maceration','Rapidase Extra Color maceration','Red-grape color/polyphenol extraction','red','receiving,maceration','crusher_or_fermentation',2,3,'g/100kg','Official range at 22-28 C','Dilute ten times before addition.','Add as early as possible at crusher or during maceration.','Verified grape weight, fruit temperature/condition, phenolic objective and enologist approval','ph,total_acidity,potential_alcohol',7,'Bentonite eliminates the enzyme; do not infer need from premium positioning.',NULL,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','rapidase batonnage','lees_ageing','Rapidase Batonnage lees-aging trial','Accelerated release from wine lees','red,white','aging','lees_ageing',2,2.5,'g/hL','Official temperature-dependent range','Dilute ten times before addition.','After approval, maintain at least four weeks contact with daily stirring and verify the applicable temperature rate.','Verified volume, lees-aging plan, sensory trial, temperature and enologist approval','ph,total_acidity,volatile_acidity',30,'Bentonite eliminates the enzyme; microbiological and oxidation risk of stirring must be controlled.',672,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','final touch gusto','pre_bottling_trial','Final touch GUSTO bench trial','Red-wine texture and tartrate-stability review','red','aging,pre-bottling','pre_bottling_bench',10,40,'mL/hL','Official Oenobrands product page','Product is soluble and may be added directly after the trial selects a rate.','Add uniformly only after sensory and tartrate-stability testing.','Verified volume, sensory bench trial, tartrate stability, sulfite/label review and enologist approval','ph,total_acidity,potassium,free_so2',30,'Contains sulfites; opened product has refrigerated-use constraints.',24,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','extraferm d tox','preventative','Extraferm D''tox preventative use','Adsorption before inoculation when supported by must condition','any','must,pre-fermentation','sanitary_evidence',20,20,'g/hL','Official preventative rate','Follow the current application sheet and homogenize.','Add before inoculation only when condition/evidence supports the stated purpose.','Verified volume, supported contamination/inhibitor risk and enologist approval','ph,total_acidity,potential_alcohol',3,'Separate 30-40 g/hL sluggish/stuck protocol; do not interchange rates.',NULL,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','extraferm d tox','sluggish_corrective','Extraferm D''tox sluggish/stuck use','Adsorb fermentation inhibitors during a supported restart','any','fermentation','sluggish_fermentation',30,40,'g/hL','Official sluggish/stuck range','Follow the current application sheet and restart protocol.','Use before the approved acclimatized restart yeast only after trajectory confirms the condition.','Verified volume, density trajectory, VA/YAN review, restart plan and enologist approval','yan,potential_alcohol,volatile_acidity',3,'This is not routine nutrition; rack/separate adsorbed inhibitors as directed by the restart protocol.',NULL,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'OENOBRANDS','anchor nourish','fermentation_nutrition','Anchor Nourish nutrition','Measured alcoholic-fermentation nutrition','any','fermentation','density_drop_30',20,40,'g/hL','Official Anchor range','Dissolve in twenty times its weight of must or warm water, avoiding lumps.','Add after lag phase; if split, make the second addition no later than half the sugar consumption.','Verified volume, linked YAN, potential alcohol, turbidity, total nutrient accounting and enologist approval','yan,potential_alcohol,turbidity',7,'Contains DAP and thiamine; local legal maximum and total inorganic nitrogen must be checked.',NULL,'Official page accessed 2026-09-15'

  UNION ALL SELECT 'ENARTIS','enartistan mel','wine_bench','EnartisTan MEL bench trial','Purpose-specific wine aging/fining trial','red,white,rose','aging','bench_trial',1,30,'mL/hL','Official color-specific ranges','Dilute in twenty parts wine.','After the lab trial selects the color/purpose-specific rate, add uniformly early in aging.','Verified volume, purpose-specific lab/sensory trial, stability/filterability review and enologist approval','ph,total_acidity',30,'White wines maximum 20 mL/hL; red maximum 30 mL/hL; contains sulfur dioxide.',168,'Official sheet accessed 2026-09-15'
  UNION ALL SELECT 'ENARTIS','enartistan clar','wine_bench','EnartisTan CLAR bench trial','Clarification or aging tannin trial','red,white','clarification,aging','bench_trial',3,10,'g/hL','Official purpose-specific ranges','Dissolve one part in ten parts water or wine.','Add during pump-over after the lab trial; when paired with gelatin add tannin first as the current sheet directs.','Verified volume, purpose/color-specific trial, filterability/stability review and enologist approval','ph,total_acidity,turbidity',30,'Juice 3-6, white wine 4-8 and red wine 5-10 g/hL are separate subranges.',24,'Official sheet accessed 2026-09-15'
  UNION ALL SELECT 'ENARTIS','enartistan skin','wine_bench','EnartisTan SKIN bench trial','Grape-tannin finishing trial','any','aging','bench_trial',3,20,'g/hL','Official Enartis page range','Follow the current technical sheet.','Add uniformly only after a recorded sensory/stability trial selects the exact rate.','Verified volume, purpose-specific bench trial, filterability/stability review and enologist approval','ph,total_acidity',30,'Do not use a catalog range as a sensory prescription.',168,'Official page accessed 2026-09-15'
  UNION ALL SELECT 'ENARTIS','enartisstab clk','tartrate_stability','EnartisStab CLK+ stability trial','Tartrate stabilization before bottling','any','pre-bottling','pre_bottling_bench',5,15,'g/hL','Official technical sheet range','Rehydrate 1:10 in wine while mixing continuously.','Use on clarified, clean wine before final microfiltration; homogenize by closed pump-over.','Verified volume, progressive trial, cold/minicontact stability test, filterability review and enologist approval','ph,total_acidity,potassium',30,'Current applicable rules and ingredient/label requirements must be checked.',24,'revision 4 March 2020'
  UNION ALL SELECT 'ENARTIS','enartispro q','microbiological_evidence','EnartisPro Q microbiological review','Supported microbial-control treatment','any','must,fermentation','sanitary_evidence',10,30,'g/hL','Official Enartis microbiological-control guidance','Disperse in twenty times its weight of water or must while preventing lumps.','Apply only for the supported microbiological objective and retest.','Verified volume, microbiological evidence/fruit condition, current chemistry and enologist approval','ph,total_acidity,volatile_acidity',3,'Contains chitosan; allergen/source and local-rule review required. Not a substitute for sanitation.',NULL,'Official guidance accessed 2026-09-15'
) x ON p.manufacturer=x.manufacturer AND p.normalized_name=x.product_key
ON DUPLICATE KEY UPDATE protocol_name=VALUES(protocol_name),purpose=VALUES(purpose),wine_colors=VALUES(wine_colors),process_stages=VALUES(process_stages),trigger_code=VALUES(trigger_code),dose_min=VALUES(dose_min),dose_max=VALUES(dose_max),dose_unit=VALUES(dose_unit),dose_basis=VALUES(dose_basis),preparation=VALUES(preparation),application_instructions=VALUES(application_instructions),prerequisites=VALUES(prerequisites),required_lab_analytes=VALUES(required_lab_analytes),lab_max_age_days=VALUES(lab_max_age_days),incompatibilities=VALUES(incompatibilities),minimum_contact_hours=VALUES(minimum_contact_hours),source_revision=VALUES(source_revision),verified_on=VALUES(verified_on),active=1;
