-- Expand the decision catalog from current official manufacturer data sheets.
-- A catalog dose range is calculator metadata, not an instruction: the
-- purpose-specific protocol, current lot evidence, and enologist decision
-- continue to govern every cellar addition.

INSERT INTO enology_product_catalog
  (id,manufacturer,product_name,normalized_name,range_code,range_name,product_class,wine_colors,process_stages,description,product_url,pds_url,dose_min,dose_max,dose_unit,dose_basis,dose_verified,source_url,source_checked_at,present_in_latest)
VALUES
  (UUID(),'ENARTIS','EnartisTan FP','enartistan fp','tannins','Tannins','tannin','red,rose','must,fermentation,aging','Condensed and hydrolysable tannin blend for color and protein stabilization; must and wine applications use separate dose bases.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFp.pdf',5,15,'g/hL','Official finished-wine range; must protocols use g/ton and remain separate.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFp.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisTan FT','enartistan ft','tannins','Tannins','tannin','any','must,fermentation,aging','Polyvalent tannin for antioxidant protection, clarification, protein/color stability and balanced structure.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFt.pdf',3,20,'g/hL','Official sheet; use the purpose-specific must or wine protocol.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFt.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisTan BLANC','enartistan blanc','tannins','Tannins','tannin','white,rose','must,aging','Gallic tannin for antioxidant and antimicrobial support, clarification, protein stability and light-struck prevention.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanBlanc.pdf',3,10,'g/hL','Official sheet; must and wine dose ranges are represented as separate protocols.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanBlanc.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisTan SKIN','enartistan skin','tannins','Tannins','tannin','any','aging,pre-bottling','White-grape-skin condensed tannin for aroma cleanliness, fruit expression, mouthfeel and color stability.','https://www.enartis.com/en-us/products/wine/tannins-en-us/grape-tannins-en-us/enartistan-skin/',NULL,3,20,'g/hL','Official Enartis product page; progressive sensory bench trial selects the rate.',1,'https://www.enartis.com/en-us/products/wine/tannins-en-us/grape-tannins-en-us/enartistan-skin/',NOW(6),1),
  (UUID(),'ENARTIS','EnartisPro TINTO','enartispro tinto','yeast_derivatives','Mannoproteins and polysaccharides','yeast_derivative','red','must,fermentation','Inactivated yeast with soluble mannoproteins plus grape-seed and ellagic tannins for red-wine color, fruit and mouthfeel.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProTinto.pdf',15,40,'g/hL','Official sheet; release horizon and color objective select the purpose-specific range.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProTinto.pdf',NOW(6),1),
  (UUID(),'ENARTIS','EnartisPro R','enartispro r','yeast_derivatives','Mannoproteins and polysaccharides','yeast_derivative','any','must,fermentation','Inactivated yeast rich in soluble mannoproteins for softness, volume, fermentation support and early stability.','https://www.enartis.com/','https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProR.pdf',20,40,'g/hL','Official sheet; white/rose and red dose ranges are represented separately.',1,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProR.pdf',NOW(6),1),
  (UUID(),'ENARTIS','NUTRIFERM AROM','nutriferm arom','nutrients','Nutrients','nutrient','any','fermentation','Autolyzed yeast with amino acids, survival factors and thiamine for measured nutrition and aromatic complexity.','https://www.enartis.com/en-us/products/wine/nutrients/organic-nutrition-en-us/nutriferm-arom/',NULL,30,30,'g/hL','Official Enartis product page; apply only within the complete YAN/APA nutrition plan.',1,'https://www.enartis.com/en-us/products/wine/nutrients/organic-nutrition-en-us/nutriferm-arom/',NOW(6),1)
ON DUPLICATE KEY UPDATE range_code=VALUES(range_code),range_name=VALUES(range_name),product_class=VALUES(product_class),wine_colors=VALUES(wine_colors),process_stages=VALUES(process_stages),description=VALUES(description),product_url=VALUES(product_url),pds_url=COALESCE(VALUES(pds_url),pds_url),dose_min=VALUES(dose_min),dose_max=VALUES(dose_max),dose_unit=VALUES(dose_unit),dose_basis=VALUES(dose_basis),dose_verified=VALUES(dose_verified),source_url=VALUES(source_url),source_checked_at=VALUES(source_checked_at),present_in_latest=1,active=1;

-- These identities and their data-sheet links already arrive from the full
-- official LAFFORT catalog sync. Add verified calculator metadata without
-- replacing the current manufacturer identity or document URL.
UPDATE enology_product_catalog p
JOIN (
  SELECT 'zymaflore vl1' k,20 lo,30 hi,'g/hL' u,'Official product data sheet' b UNION ALL
  SELECT 'zymaflore vl2',20,30,'g/hL','Official product data sheet' UNION ALL
  SELECT 'zymaflore cx9',20,30,'g/hL','Official product data sheet' UNION ALL
  SELECT 'zymaflore xorigin',20,30,'g/hL','Official product data sheet' UNION ALL
  SELECT 'zymaflore xpure',20,30,'g/hL','Official product data sheet' UNION ALL
  SELECT 'zymaflore rb2',20,30,'g/hL','Official product data sheet' UNION ALL
  SELECT 'zymaflore fx10',20,30,'g/hL','Official product data sheet' UNION ALL
  SELECT 'lafazym cl',0.5,4,'g/hL','Official purpose-specific clarification ranges' UNION ALL
  SELECT 'extraclear',3,6,'mL/hL','Official timing-specific clarification ranges' UNION ALL
  SELECT 'extralyse',6,10,'g/hL','Official filtration and lees-aging ranges' UNION ALL
  SELECT 'nutristart arom',20,60,'g/hL','Official range; calculate from YAN/APA, potential alcohol, turbidity and yeast strain' UNION ALL
  SELECT 'nutristart org',30,60,'g/hL','Official range; adjust to measured nitrogen need' UNION ALL
  SELECT 'nutriflow',50,250,'mL/hL','Official range; adjust to measured nitrogen need' UNION ALL
  SELECT 'maloboost',20,40,'g/hL','Official normal and sluggish-MLF ranges' UNION ALL
  SELECT 'powerlees',15,40,'g/hL','Official range according to desired fermentation effect' UNION ALL
  SELECT 'oenolees',20,40,'g/hL','Official range according to sensory and fining objective' UNION ALL
  SELECT 'oenobrett org',4,10,'g/hL','Official Brettanomyces-control range; maximum EU dose 10 g/hL' UNION ALL
  SELECT 'polymust blanc',30,80,'g/hL','Official must/wine fining range; bench trial required' UNION ALL
  SELECT 'vegemust',5,40,'g/hL','Official must and wine ranges; bench trial required' UNION ALL
  SELECT 'tanin vr skin',10,80,'g/hL','Official purpose-specific ranges'
) x ON p.manufacturer='LAFFORT' AND p.normalized_name=x.k
SET p.dose_min=x.lo,p.dose_max=x.hi,p.dose_unit=x.u,p.dose_basis=x.b,p.dose_verified=1,p.source_checked_at=NOW(6),p.active=1,p.present_in_latest=1;

INSERT INTO enology_product_protocols
  (id,product_catalog_id,protocol_code,protocol_name,purpose,wine_colors,process_stages,trigger_code,dose_min,dose_max,dose_unit,dose_basis,preparation,application_instructions,prerequisites,required_lab_analytes,lab_max_age_days,incompatibilities,minimum_contact_hours,source_url,source_revision,verified_on)
SELECT UUID(),p.id,x.protocol_code,x.protocol_name,x.purpose,x.wine_colors,x.process_stages,x.trigger_code,x.dose_min,x.dose_max,x.dose_unit,x.dose_basis,x.preparation,x.application_instructions,x.prerequisites,x.required_lab_analytes,x.lab_max_age_days,x.incompatibilities,x.minimum_contact_hours,x.source_url,x.source_revision,'2026-09-16'
FROM enology_product_catalog p
JOIN (
  SELECT 'LAFFORT' m,'zymaflore vl1' k,'standard_inoculation' protocol_code,'White-wine inoculation' protocol_name,'Fine white-wine fermentation' purpose,'white' wine_colors,'must,pre-fermentation' process_stages,'inoculation' trigger_code,20 dose_min,30 dose_max,'g/hL' dose_unit,'Official product data sheet' dose_basis,'Follow the current packet rehydration protocol.' preparation,'Inoculate promptly after rehydration and homogenize.' application_instructions,'Verified volume, must temperature, potential alcohol, YAN/APA and selected yeast' prerequisites,'ph,total_acidity,potential_alcohol,yan' required_lab_analytes,7 lab_max_age_days,'Keep the must and yeast suspension temperature difference below 10 C; total preparation time must remain below 45 minutes.' incompatibilities,NULL minimum_contact_hours,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_VL1.pdf' source_url,'current sheet accessed 2026-09-16' source_revision
  UNION ALL SELECT 'LAFFORT','zymaflore vl2','standard_inoculation','White-wine inoculation','White-wine fermentation with polysaccharide contribution','white','must,pre-fermentation','inoculation',20,30,'g/hL','Official product data sheet','Follow the current packet rehydration protocol.','Inoculate promptly after rehydration and homogenize.','Verified volume, temperature, potential alcohol, YAN/APA, turbidity and selected yeast','ph,total_acidity,potential_alcohol,yan,turbidity',7,'Keep the must and yeast suspension temperature difference below 10 C.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_VL2.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','zymaflore cx9','standard_inoculation','White-wine inoculation','Complex white-wine fermentation','white','must,pre-fermentation','inoculation',20,30,'g/hL','Official product data sheet','Follow the current packet rehydration protocol.','Inoculate promptly after rehydration and homogenize.','Verified volume, temperature, potential alcohol, YAN/APA and turbidity','ph,total_acidity,potential_alcohol,yan,turbidity',7,'Keep the must and yeast suspension temperature difference below 10 C.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_CX9.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','zymaflore xorigin','standard_inoculation','White-wine inoculation','Balanced white-wine fermentation respecting fruit and origin','white','must,pre-fermentation','inoculation',20,30,'g/hL','Official product data sheet','Follow the current packet rehydration protocol.','Inoculate promptly after rehydration and homogenize.','Verified volume, temperature, potential alcohol, YAN/APA and turbidity','ph,total_acidity,potential_alcohol,yan,turbidity',7,'Keep the must and yeast suspension temperature difference below 10 C.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_XOrigin.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','zymaflore xpure','standard_inoculation','Red-wine inoculation','Aromatically clean red-wine fermentation','red','must,pre-fermentation','inoculation',20,30,'g/hL','Official product data sheet','Follow the current packet rehydration protocol.','Inoculate promptly after rehydration and homogenize.','Verified volume, temperature, potential alcohol, YAN/APA and selected yeast','ph,total_acidity,potential_alcohol,yan',7,'Cold soak has a separate split-inoculation protocol; do not silently use the standard range.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_Xpure.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','zymaflore rb2','standard_inoculation','Red-wine inoculation','Fruit-forward red-wine fermentation','red','must,pre-fermentation','inoculation',20,30,'g/hL','Official product data sheet','Follow the current packet rehydration protocol.','Inoculate promptly after rehydration and homogenize.','Verified volume, temperature, potential alcohol, YAN/APA and selected yeast','ph,total_acidity,potential_alcohol,yan',7,'Cold soak has a separate split-inoculation protocol; do not silently use the standard range.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_RB2.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','zymaflore fx10','standard_inoculation','Red-wine inoculation','Structured red-wine fermentation','red','must,pre-fermentation','inoculation',20,30,'g/hL','Official product data sheet','Follow the current packet rehydration protocol.','Inoculate promptly after rehydration and homogenize.','Verified volume, temperature, potential alcohol, YAN/APA and selected yeast','ph,total_acidity,potential_alcohol,yan',7,'Cold soak has a separate split-inoculation protocol; do not silently use the standard range.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Zymaflore_FX10.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','lafazym cl','free_run_settling','Free-run juice clarification','Reduce viscosity and reach the selected settling turbidity','white,rose','pressing,must,clarification','must_clarification',0.5,2,'g/hL','Official free-run must range','Dissolve and homogenize according to the current sheet.','Add uniformly to free-run juice; select within the range from variety, ripeness, sanitation, temperature and target turbidity.','Verified juice volume, temperature, turbidity target and pectin-test plan','ph,total_acidity,turbidity',3,'Bentonite inactivates pectolytic enzymes; confirm completion with a pectin test before bentonite.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Lafazym_CL.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','extraclear','during_af','Fermentation clarification enzyme','Improve clarification and filterability when added during the last third of AF','any','fermentation','clarification_enzyme',3,6,'mL/hL','Official during-AF range','Dilute and homogenize according to the current sheet.','Add from the last third of alcoholic fermentation and allow at least 5-7 days contact.','Verified volume, active fermentation stage and filtration objective','turbidity',3,'Do not collapse the during-AF and post-AF ranges.',120,'https://laffort.com/wp-content/uploads/FP/FP_EN_Extraclear.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','extralyse','filtration','Post-fermentation filtration enzyme','Improve clarification, microbial stability and filtration','any','post-fermentation,clarification,aging','clarification_enzyme',6,6,'g/hL','Official filtration range','Dissolve and homogenize according to the current sheet.','Add after fermentation and allow at least 5-7 days before filtration.','Verified volume, completed AF, filtration plan and glucan/clarification need','turbidity',7,'Lees-aging use has a separate 6-10 g/hL and 3-6 week protocol.',120,'https://laffort.com/wp-content/uploads/FP/FP_EN_Extralyse.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','nutristart arom','first_third','Aromatic fermentation nutrition','Correct a measured light-to-moderate nitrogen need while supporting aroma','white,rose','fermentation','density_drop_30',20,60,'g/hL','Official sheet; calculate from must composition','Dissolve and homogenize according to the current sheet.','Add according to the measured nutrition plan, normally within the first third of fermentation.','Verified volume, YAN/APA, potential alcohol, turbidity, yeast strain and total nutrient accounting','yan,potential_alcohol,turbidity',7,'Do not select a rate from YAN deficit alone or stack nitrogen sources without total accounting.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Nutristart_Arom.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','nutristart org','first_third','Organic fermentation nutrition','Correct a measured nitrogen need with a yeast-derived nutrient','any','fermentation','density_drop_30',30,60,'g/hL','Official range adjusted to measured need','Dissolve and homogenize according to the current sheet.','Add according to the complete measured nutrition plan.','Verified volume, YAN/APA, potential alcohol, turbidity, yeast strain and total nutrient accounting','yan,potential_alcohol,turbidity',7,'Severe deficiency or high alcohol requires a separately reviewed balanced plan.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Nutristart_Org.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','nutriflow','measured_nutrition','Liquid organic fermentation nutrition','Correct a measured nitrogen need with a liquid yeast-derived nutrient','any','fermentation','density_drop_30',50,250,'mL/hL','Official range adjusted to measured need','Use the liquid product through a clean calibrated addition system.','Add at fermentation start or after the first third only as selected by the complete nutrition plan.','Verified volume, YAN/APA, potential alcohol, turbidity, yeast strain and total nutrient accounting','yan,potential_alcohol,turbidity',7,'Do not infer a dose only from the product nitrogen-equivalence statement.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Nutriflow.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','maloboost','standard_mlf','MLF activation','Facilitate and accelerate a supported malolactic fermentation plan','any','fermentation,post-fermentation,aging','mlf_activation',20,30,'g/hL','Official standard-MLF range','Dissolve in water or wine according to the current sheet.','Add 24 hours before the selected bacteria and homogenize without oxygen pickup.','Verified volume, MLF plan, temperature, pH, alcohol and malic-acid result','ph,actual_alcohol,malic_acid',3,'Sluggish or blocked MLF uses a separate 30-40 g/hL protocol.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Maloboost.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','powerlees','fermentation','Fermentation mouthfeel support','Build mouthfeel and reduce astringency from the outset of AF','any','fermentation','crusher_or_fermentation',15,40,'g/hL','Official range according to desired effect','Disperse and homogenize according to the current sheet.','Add at the beginning of alcoholic fermentation only after the stylistic objective is recorded.','Verified volume, fermentation stage, sensory objective and selected rate','ph,total_acidity,potential_alcohol',7,'This is not a substitute for yeast nutrition.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Powerlees.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','oenolees','wine_fining','Wine fining and mouthfeel bench trial','Improve balance and selectively reduce aggressive phenolics','any','post-fermentation,clarification,aging','bench_trial',20,40,'g/hL','Official range according to desired effect','Dissolve and homogenize according to the current sheet.','Run a progressive laboratory and sensory trial before the cellar addition.','Verified volume, finished AF/MLF status, sensory objective and recorded trial','ph,total_acidity,turbidity',30,'Assess settling, filterability and sensory effect after the trial.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Oenolees.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','oenobrett org','brett_control','Brettanomyces control','Reduce a laboratory-confirmed undesirable Brettanomyces population after AF and MLF','any','post-fermentation,aging','microbial_control',4,10,'g/hL','Official range; EU maximum 10 g/hL','Dissolve in ten times its weight of water or wine and homogenize thoroughly.','Treat only after AF and MLF, then reassess microbiology; racking is possible after eight days.','Verified volume, completed AF/MLF, current Brettanomyces result and SO2 plan','brettanomyces,ph,free_so2',3,'Do not use as a preventive default or exceed the applicable legal maximum.',192,'https://laffort.com/wp-content/uploads/FP/FP_EN_Oenobrett_ORG.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','polymust blanc','white_must','White/rose must fining bench trial','Manage oxidizable phenolics and clarification in must or fermenting wine','white,rose','must,fermentation,clarification','bench_trial',30,80,'g/hL','Official range; progressive bench trial selects the rate','Prepare and add according to the current sheet.','Run a progressive laboratory trial, record the selected rate and homogenize the approved addition.','Verified volume, turbidity, oxidation objective and recorded trial','ph,total_acidity,turbidity,catechins',3,'Do not automatically choose the maximum; legal maximum is 80 g/hL.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Polymust_Blanc.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','vegemust','must_fining','Must fining bench trial','Plant-protein clarification and phenolic management in white or rose must','white,rose','must,clarification','bench_trial',10,40,'g/hL','Official white/rose must range','Prepare and add according to the current sheet.','Run a progressive bench trial and record the selected rate before addition.','Verified volume, turbidity, phenolic/oxidation objective and recorded trial','ph,total_acidity,turbidity,catechins',3,'Wine use has a separate 5-20 g/hL range; EU maximum is 50 g/hL.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Vegemust.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'LAFFORT','tanin vr skin','colour','Red-wine color stabilization','Support color stabilization at the first pump-over','red','must,fermentation','first_pump_over',20,40,'g/hL','Official color-stabilization range','No preliminary dissolution is required by the current product process; homogenize thoroughly.','Add during a recorded pump-over only after the phenolic objective is confirmed.','Verified volume, fruit condition, phenolic objective and selected rate','ph,total_acidity,potential_alcohol',7,'Clarification and laccase-control uses have separate dose ranges.',NULL,'https://laffort.com/wp-content/uploads/FP/FP_EN_Tanin_VR_Skin.pdf','current sheet accessed 2026-09-16'

  UNION ALL SELECT 'ENARTIS','enartistan fp','sound_must','Sound-fruit must color protection','Protein and color stabilization during red or rose must processing','red,rose','receiving,must,fermentation','crusher_or_fermentation',150,300,'g/ton','Official sound-fruit must range','Dissolve 1:10 in water, wine or must while mixing continuously.','Add uniformly during pump-over with a dosing pump or Venturi.','Recorded fruit weight and condition, chemistry, phenolic objective and selected rate','ph,total_acidity,potential_alcohol',7,'Moldy fruit has a separate 150-400 g/ton range.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFp.pdf','revision 2 June 2020'
  UNION ALL SELECT 'ENARTIS','enartistan fp','wine_bench','Wine tannin bench trial','Color/protein stabilization during maturation','red,rose','aging','bench_trial',5,15,'g/hL','Official wine range','Dissolve 1:10 in water, wine or must while mixing continuously.','Add only after a recorded laboratory and sensory trial selects the rate.','Verified wine volume, current chemistry, stability review and recorded trial','ph,total_acidity',30,'Check filterability plus protein and colloidal stability near bottling.',168,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFp.pdf','revision 2 June 2020'
  UNION ALL SELECT 'ENARTIS','enartistan ft','must','Must tannin program','Antioxidant, clarification, protein/color stability and structure support','any','must,fermentation','crusher_or_fermentation',10,20,'g/hL','Official must range','Dissolve and homogenize according to the current sheet.','Add only after the purpose and exact rate are selected.','Verified volume, chemistry, fruit condition and phenolic objective','ph,total_acidity,potential_alcohol',7,'Finished wine uses a separate 3-10 g/hL bench-trial protocol.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanFt.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'ENARTIS','enartistan blanc','must','White/rose must tannin','Antioxidant support, clarification, protein stability and light-struck prevention','white,rose','must,fermentation','crusher_or_fermentation',3,10,'g/hL','Official must range','Dissolve 1:10 in water, must or wine and mix continuously.','Add slowly while mixing or during pump-over.','Verified volume, chemistry, oxidation/protein objective and selected rate','ph,total_acidity,turbidity',7,'Finished wine uses a separate 4-8 g/hL bench trial.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-TanBlanc.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'ENARTIS','enartistan skin','wine_bench','Grape-skin tannin bench trial','Improve fruit, mouthfeel, complexity and color stability during maturation','any','aging,pre-bottling','pre_bottling_bench',3,20,'g/hL','Official product-page range','Dissolve and homogenize according to the current sheet.','Use a progressive sensory trial to select the exact rate.','Verified wine volume, sensory objective and recorded trial','ph,total_acidity',30,'Verify filterability and colloidal stability before bottling.',168,'https://www.enartis.com/en-us/products/wine/tannins-en-us/grape-tannins-en-us/enartistan-skin/','official page accessed 2026-09-16'
  UNION ALL SELECT 'ENARTIS','enartispro tinto','young_red','Young-red fermentation program','Protect color and build fruit and mouthfeel for early-release red wine','red','must,fermentation','crusher_or_fermentation',15,20,'g/hL','Official young-wine range','Disperse in water or must and homogenize.','Add at the beginning of fermentation while filling or during pump-over.','Verified volume, release horizon, chemistry and color objective','ph,total_acidity,potential_alcohol',7,'Medium/long storage uses a separate 30-40 g/hL range.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProTinto.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'ENARTIS','enartispro r','white_rose','White/rose fermentation mannoprotein program','Build softness and volume while supporting early stability','white,rose','must,fermentation','crusher_or_fermentation',20,30,'g/hL','Official white/rose range','Disperse in ten times its weight of water or must.','Add at the beginning of fermentation while filling, then mix by pump-over.','Verified volume, chemistry, release objective and selected rate','ph,total_acidity,potential_alcohol',7,'Red wine uses a separate 30-40 g/hL range.',NULL,'https://www.enartis.com/datasheets/TECHNICAL-DATA-SHEET/EN/TDS-EN-ProR.pdf','current sheet accessed 2026-09-16'
  UNION ALL SELECT 'ENARTIS','nutriferm arom','first_third','Aromatic organic nutrition','Support measured fermentation nutrition and aroma complexity','any','fermentation','density_drop_30',30,30,'g/hL','Official product-page rate','Dissolve and homogenize according to the current sheet.','Add only as part of the complete measured nutrition plan.','Verified volume, YAN/APA, potential alcohol, turbidity, yeast strain and total nutrient accounting','yan,potential_alcohol,turbidity',7,'Do not stack with other nitrogen products without total accounting.',NULL,'https://www.enartis.com/en-us/products/wine/nutrients/organic-nutrition-en-us/nutriferm-arom/','official page accessed 2026-09-16'
) x ON p.manufacturer=x.m AND p.normalized_name=x.k
ON DUPLICATE KEY UPDATE protocol_name=VALUES(protocol_name),purpose=VALUES(purpose),wine_colors=VALUES(wine_colors),process_stages=VALUES(process_stages),trigger_code=VALUES(trigger_code),dose_min=VALUES(dose_min),dose_max=VALUES(dose_max),dose_unit=VALUES(dose_unit),dose_basis=VALUES(dose_basis),preparation=VALUES(preparation),application_instructions=VALUES(application_instructions),prerequisites=VALUES(prerequisites),required_lab_analytes=VALUES(required_lab_analytes),lab_max_age_days=VALUES(lab_max_age_days),incompatibilities=VALUES(incompatibilities),minimum_contact_hours=VALUES(minimum_contact_hours),source_url=VALUES(source_url),source_revision=VALUES(source_revision),verified_on=VALUES(verified_on),active=1;
